from pathlib import Path
import re

p = Path('index.html')
s = p.read_text(encoding='utf-8')

# Remove every previous AI overlay. Keep the original Vue itinerary untouched.
s = re.sub(r'<script id="AI_ITINERARY_ASSISTANT_V1">.*?</script>\s*', '', s, flags=re.S)
s = re.sub(r'<script id="AI_ITINERARY_REPAIR_V2">.*?</script>\s*', '', s, flags=re.S)
s = re.sub(r'<script id="AI_ITINERARY_REPAIR_V3">.*?</script>\s*', '', s, flags=re.S)
s = s.replace('<script>window.alert = function() {};</script>\n', '')
s = s.replace('<script>window.alert = function() {};</script>', '')

script = r'''
<script id="AI_ITINERARY_REPAIR_V4">
(function(){
  const KEY='okinawa_ai_endpoint', ITIN='oki_sleek_itin', BACK='oki_sleek_itin_ai_backup';
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const endpoint=()=>String(localStorage.getItem(KEY)||'').trim().replace(/\/$/,'');
  const read=(key,def)=>{try{const x=JSON.parse(localStorage.getItem(key)||'null');return x??def}catch(e){return def}};
  const getList=()=>{const x=read(ITIN,[]);return Array.isArray(x)?x:[]};
  const getSafeList=()=>{const x=getList();if(x.length)return x;const b=read(BACK,[]);return Array.isArray(b)?b:[]};
  const backup=()=>{const x=getList();if(x.length) localStorage.setItem(BACK,JSON.stringify(x));};
  backup();
  const modal=()=>document.getElementById('ai-itinerary-modal'), result=()=>document.getElementById('ai-result');
  function err(m){const e=result();if(e)e.innerHTML='<div style="padding:14px;border-radius:16px;background:#fff4e8;color:#9a6b3a;font-size:11px;line-height:1.7">AI 暫時無法回覆。<br>'+esc(m||'連線失敗')+'</div>'}
  function close(){const m=modal();if(m)m.remove()}
  function configure(){const v=prompt('貼上 AI Worker 網址',endpoint());if(v===null)return;const x=v.trim().replace(/\/$/,'');if(x)localStorage.setItem(KEY,x);else localStorage.removeItem(KEY);alert(x?'AI 連線網址已儲存。':'已清除 AI 連線網址。')}
  async function test(){const b=endpoint();if(!b){configure();return false}try{const r=await fetch(b+'/health?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json().catch(()=>({}));alert('AI 後端連線成功！\n內建景點資料：'+(j.places||'可用'));return true}catch(e){alert('AI 後端目前無法連線：'+e.message);return false}}
  function open(kind){close();const m=document.createElement('div');m.id='ai-itinerary-modal';m.dataset.mode=kind;m.style='position:fixed;inset:0;z-index:9999;background:rgba(24,63,70,.45);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:14px';m.innerHTML='<div style="width:min(100%,520px);background:#f7f6f0;border-radius:28px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.2);max-height:88vh;overflow:auto"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:9px;letter-spacing:.22em;color:#78B6B2;font-weight:900">AI ITINERARY</div><div style="font:700 24px Georgia;color:#183F46;margin-top:4px">'+(kind==='replan'?'AI 重新編排行程':'AI 幫我新增景點')+'</div></div><button type="button" onclick="window.closeAIItinerary()" style="border:0;background:white;border-radius:12px;width:36px;height:36px">×</button></div><div style="display:flex;gap:7px;margin-top:10px"><button type="button" onclick="window.configureAI()" style="flex:1;border:1px solid #dce2df;background:white;border-radius:12px;padding:9px;font-size:10px;font-weight:800;color:#183F46">⚙ 設定 AI 連線</button><button type="button" onclick="window.testAI()" style="flex:1;border:1px solid #dce2df;background:white;border-radius:12px;padding:9px;font-size:10px;font-weight:800;color:#183F46">測試連線</button></div><p style="font-size:11px;color:#7a8582;line-height:1.7;margin:10px 0">AI 會參考目前四天完整行程；新增只增加景點，不會覆蓋其他日期。即使 AI API 暫時不可用，也會使用沖繩內建景點資料。</p><div style="display:grid;grid-template-columns:1fr 100px;gap:8px"><input id="ai-place-input" placeholder="例如：首里城、瀨長島、國際通、萬座毛" style="border:1px solid #dce2df;border-radius:14px;padding:12px;font-size:12px;background:white;outline:none"><select id="ai-day-input" style="border:1px solid #dce2df;border-radius:14px;padding:12px;font-size:12px;background:white"><option>DAY 1</option><option>DAY 2</option><option>DAY 3</option><option>DAY 4</option></select></div><button type="button" onclick="window.runAIItinerary()" style="width:100%;margin-top:9px;border:0;border-radius:15px;padding:12px;background:#183F46;color:white;font-weight:900;font-size:11px">開始整理</button><div id="ai-result" style="margin-top:12px"></div><div style="font-size:9px;color:#9aa29f;margin-top:10px">AI Key 不會放在 GitHub Pages。</div></div>';document.body.appendChild(m)}
  window.openAIItineraryAdd=()=>open('add');window.openAIItineraryReplan=()=>open('replan');window.closeAIItinerary=close;window.configureAI=configure;window.testAI=test;
  window.runAIItinerary=async function(){const p=(document.getElementById('ai-place-input')?.value||'').trim(),d=document.getElementById('ai-day-input')?.value||'DAY 1',e=result();if(!p){if(e)e.innerHTML='<div style="padding:12px;background:#fff4e8;border-radius:14px;color:#9a6b3a;font-size:11px">請先輸入景點或需求。</div>';return}const b=endpoint();if(!b){err('尚未設定 AI Worker。你仍可先設定 Worker 後使用完整 AI；若沒有 Worker，無法取得詳細 AI 資訊。');return}backup();if(e)e.innerHTML='<div style="padding:14px;border-radius:16px;background:white;color:#7a8582;font-size:11px">AI 正在分析目前四天行程，尋找順路位置…</div>';try{const r=await fetch(b+'/v1/itinerary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:modal()?.dataset.mode||'add',place:p,day:d,trip:read('oki_sleek_tripinfo',{}),itinerary:getSafeList()})}),data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw Error(data.error||'HTTP '+r.status);window.__aiPendingResult=data.result||{};window.__aiReordered=Array.isArray(data.reorderedItinerary)?data.reorderedItinerary:[];window.__aiSource=data.source||'built-in';render(data.result||{},d,p,modal()?.dataset.mode||'add',window.__aiReordered,window.__aiSource)}catch(x){err(x.message)}};
  function render(r,d,p,mode,reordered,source){const e=result();if(!e)return;const title=r.title||p,src=source==='openai'?'✨ OpenAI AI':'🟡 沖繩內建資料';const maps=r.mapsUrl||('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(title+' 沖繩'));const official=r.officialUrl||'';if(mode==='replan'){const a=reordered.length?reordered:[r];e.innerHTML='<div style="background:white;border:1px solid #dce2df;border-radius:18px;padding:15px"><div style="font-size:9px;color:#78B6B2;font-weight:900">'+esc(d)+' · '+src+'</div><div style="font:700 20px Georgia;color:#183F46;margin-top:3px">AI 順路重新編排</div><div style="font-size:10px;color:#7a8582;margin-top:5px">只會替換 '+esc(d)+'，其他三天完全保留。</div><div style="margin-top:12px">'+a.map(x=>'<div style="padding:9px 0;border-top:1px solid #edf0ee;font-size:11px"><b>'+esc(x.time||'待定')+'</b>　'+esc(x.title||'行程')+'<br><span style="font-size:9px;color:#7a8582">'+esc(x.locationHint||'')+' · '+esc(x.stayDuration||'')+'</span></div>').join('')+'</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px"><button type="button" onclick="window.applyAIReplan()" style="border:0;border-radius:14px;padding:11px;background:#78B6B2;color:white;font-weight:900;font-size:11px">套用重新編排</button><button type="button" onclick="window.closeAIItinerary()" style="border:1px solid #dce2df;border-radius:14px;padding:11px;background:white;color:#183F46;font-weight:900;font-size:11px">先不要變更</button></div></div>';return}e.innerHTML='<div style="background:white;border:1px solid #dce2df;border-radius:18px;padding:15px"><div style="font-size:9px;color:#78B6B2;font-weight:900">'+esc(r.day||d)+' · '+src+'</div><div style="font:700 20px Georgia;color:#183F46;margin-top:3px">'+esc(title)+'</div><div style="margin-top:12px;font-size:11px;color:#53615f;line-height:1.75"><b>📍 所在區域</b><br>'+esc(r.locationHint||'待確認')+'<br><b>🕐 建議時間</b>　'+esc(r.time||'待確認')+'<br><b>⏱ 建議停留</b>　'+esc(r.stayDuration||'待確認')+'<br><b>🚌 交通方向</b><br>'+esc(r.transitMode||'待確認')+'<br><b>📝 景點提醒</b><br>'+esc(r.note||'目前沒有額外說明。')+'</div><div style="display:grid;grid-template-columns:1fr '+(official?'1fr':'0fr')+';gap:7px;margin-top:12px"><a href="'+esc(maps)+'" target="_blank" rel="noopener" style="text-align:center;text-decoration:none;border-radius:14px;padding:11px;background:#DDEDEA;color:#183F46;font-weight:900;font-size:11px">開 Google Maps</a>'+(official?'<a href="'+esc(official)+'" target="_blank" rel="noopener" style="text-align:center;text-decoration:none;border-radius:14px;padding:11px;background:#eef3f1;color:#183F46;font-weight:900;font-size:11px">官方網站</a>':'')+'</div><button type="button" onclick="window.aiSaveStop()" style="width:100%;margin-top:7px;border:0;border-radius:14px;padding:11px;background:#78B6B2;color:white;font-weight:900;font-size:11px">加入今天行程</button></div>'}
  window.aiSaveStop=function(){const r=window.__aiPendingResult||{},old=getSafeList(),n=Number(String(r.day||document.getElementById('ai-day-input')?.value||'DAY 1').replace(/\D/g,''))||1;if(!old.length){err('找不到原本行程，為安全起見沒有寫入任何資料。');return}const item={day:n,time:r.time||'12:00',stayDuration:r.stayDuration||'1 小時',transitTimeToNext:r.transitTimeToNext||'待確認',transitKm:r.transitKm||'待確認',title:r.title||'AI 建議景點',transitMode:r.transitMode||'大眾運輸',locationHint:r.locationHint||'沖繩本島',officialUrl:r.officialUrl||'',mapsUrl:r.mapsUrl||('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(r.title||'沖繩景點')),note:r.note||'AI 建議行程'};const next=old.concat(item);if(next.length!==old.length+1){err('安全檢查失敗，沒有覆寫原本行程。');return}localStorage.setItem(BACK,JSON.stringify(old));localStorage.setItem(ITIN,JSON.stringify(next));localStorage.setItem('oki_sleek_active_day',String(n));if(JSON.stringify(read(ITIN,[]))!==JSON.stringify(next)){localStorage.setItem(ITIN,JSON.stringify(old));err('儲存驗證失敗，已保留原本行程。');return}alert('已加入 DAY '+n+'：'+item.title+'\n原本四天行程全部保留。');location.reload()};
  window.applyAIReplan=function(){const a=Array.isArray(window.__aiReordered)?window.__aiReordered:[],old=getSafeList();if(!a.length||!old.length)return;const d=Number(String(a[0]?.day||document.getElementById('ai-day-input')?.value||'DAY 1').replace(/\D/g,''))||1,keep=old.filter(x=>Number(x?.day)!==d),clean=a.map(x=>({...x,day:Number(x.day)||d})),next=keep.concat(clean);if(old.filter(x=>Number(x?.day)===d).length===0)return;localStorage.setItem(BACK,JSON.stringify(old));localStorage.setItem(ITIN,JSON.stringify(next));if(JSON.stringify(read(ITIN,[]))!==JSON.stringify(next)){localStorage.setItem(ITIN,JSON.stringify(old));alert('儲存驗證失敗，原本行程已保留。');return}localStorage.setItem('oki_sleek_active_day',String(d));alert('DAY '+d+' 已重新編排；其他天沒有變更。');location.reload()};
})();
</script>
'''
s = s.replace('</body>', script + '</body>', 1)
p.write_text(s, encoding='utf-8')
